apiVersion: v1
kind: Service
metadata:
  name: expo-loadbalancer
spec:
  # Jeito preferido para expor as aplicações em produção.
  # Ele tenta se integrar ao provedor onde ele está rodando
  # para tentar criar esse dispositivo de load balancer.
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # Como eu não tenho nenhum dispositivo de Load balancer instalado, eu posso
  # informar para o kubernetes com qual IP ele deve trabalhar.
  externalIPs:
    - 143.198.184.58

# kubectl apply -f service-loadbalancer.yaml
# kubectl get services
